### ISSUE TITLE
airbyte integration with R2

### ISSUE THREAD

**Issue by kananindzya** [alexmojaki/s3-stream-upload#46]
Hi @alexmojaki ,
At current time I am working on airbyte destination for R2(https://www.cloudflare.com/products/r2/).
And started to test it with current airbyte s3 destination. 
Airbyte do internal checks with singleUpload and multipartUpload cases. https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java#L113

In addition I rebuild airbyte's s3 destination with your latest version and tested it locally, same error as below.

Below provided error logs on airbyte's check step:

```
19: "2022-08-08 11:37:58 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:37:58 \u001b[32mINFO\u001b[m i.a.i.d.s.S3Destination(testIAMUserHasListObjectPermission):158 - Finished checking for listObjects permission"
20: "2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.i.d.s.S3Destination(testSingleUpload):81 - Started testing if all required credentials assigned to user for single file uploading"
21: "2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.i.d.s.S3Destination(testSingleUpload):91 - Finished checking for normal upload mode"
22: "2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:37:59 \u001b[32mINFO\u001b[m i.a.i.d.s.S3Destination(testMultipartUpload):95 - Started testing if all required credentials assigned to user for multipart upload"
23: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[32mINFO\u001b[m a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to xxx/test/hello5/test_1659958679978 with full ID ADUpbvgxbBwPD4AyyislPzRWHsSVVfuteGRLTQfA+OexzZ222lxM+CPoQHcTM78Bqb6U5Kb7deOldkB8jHO+X1Jf4uEjkRldvVAKF+p5XZNSOn1wld6+RS3/8CHGP8zb50rvzX8rHuSWiYtyLYCHpS19zuI65tFCCVk/5FVvzu50I0zko+eOq5Fy2KI38A8RDACUDuPWdks6Httj+KAUkUryQ/Disc0twakt3DGLRTuRjZ1UwZvvhTVjTQA8WKWbO7sLFptNb2DhUM1vOU9I/zTrkx8oOVALvCvaGtPB3bVsbuStSKGNKUuPGYIUsAu+8g=="
24: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[32mINFO\u001b[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]"
25: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[32mINFO\u001b[m a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]"
26: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[33mWARN\u001b[m a.m.s.MultiPartOutputStream(close):160 - [MultipartOutputStream for parts 1 - 10000] is already closed"
27: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[32mINFO\u001b[m a.m.s.StreamTransferManager(complete):367 - [Manager uploading to xxx/test/hello5/test_1659958679978 with id ADUpbvgxb...UsAu+8g==]: Uploading leftover stream [Part number 1 containing 3.34 MB]"
28: "2022-08-08 11:38:00 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:00 \u001b[32mINFO\u001b[m a.m.s.StreamTransferManager(uploadStreamPart):556 - Upload request = com.amazonaws.services.s3.model.UploadPartRequest@4b74b35"
29: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:01 \u001b[1;31mERROR\u001b[m a.m.s.StreamTransferManager(abort):434 - Aborting [Manager uploading to xxx/test/hello5/test_1659958679978 with id ADUpbvgxb...UsAu+8g==] due to error: java.lang.IllegalArgumentException: Invalid base 16 character: 'K'"
30: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:01 \u001b[32mINFO\u001b[m a.m.s.StreamTransferManager(abort):472 - [Manager uploading to xxx/test/hello5/test_1659958679978 with id ADUpbvgxb...UsAu+8g==]: Aborted"
31: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:01 \u001b[1;31mERROR\u001b[m i.a.i.d.s.S3Destination(check):72 - Exception attempting to access the S3 bucket: "
32: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - java.lang.IllegalArgumentException: Invalid base 16 character: 'K'"
33: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.util.Base16Codec.pos(Base16Codec.java:100) ~[aws-java-sdk-core-1.12.6.jar:?]"
34: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.util.Base16Codec.decode(Base16Codec.java:87) ~[aws-java-sdk-core-1.12.6.jar:?]"
35: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.util.Base16Lower.decode(Base16Lower.java:53) ~[aws-java-sdk-core-1.12.6.jar:?]"
36: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:48) ~[aws-java-sdk-core-1.12.6.jar:?]"
37: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3881) ~[aws-java-sdk-s3-1.12.6.jar:?]"
38: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3860) ~[aws-java-sdk-s3-1.12.6.jar:?]"
39: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat alex.mojaki.s3upload.StreamTransferManager.uploadStreamPart(StreamTransferManager.java:557) ~[s3-stream-upload-2.2.5.jar:?]"
40: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat alex.mojaki.s3upload.StreamTransferManager.complete(StreamTransferManager.java:368) ~[s3-stream-upload-2.2.5.jar:?]"
41: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat io.airbyte.integrations.destination.s3.S3Destination.testMultipartUpload(S3Destination.java:113) ~[io.airbyte.airbyte-integrations.connectors-destination-s3-0.39.41-alpha.jar:?]"
42: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat io.airbyte.integrations.destination.s3.S3Destination.check(S3Destination.java:68) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.39.41-alpha.jar:?]"
43: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:121) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]"
44: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]"
45: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - \tat io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:51) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.39.41-alpha.jar:?]"
46: "2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-08-08 11:38:01 \u001b[32mINFO\u001b[m i.a.i.b.IntegrationRunner(runInternal):152 - Completed integration: io.airbyte.integrations.destination.s3.S3Destination"
47: "2022-08-08 11:38:02 \u001b[32mINFO\u001b[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling..."
```

On cloudflare form I found related problem with `Etag`.
https://community.cloudflare.com/t/r2-multipart-upload-not-working-with-minio-client-mc/396373

Do you know what can be cause of this error?

**Comment by kananindzya** [comment]
Hi @alexmojaki ,
this I solved with workaround - `StreamTransferManager#computeCompleteFileETag`:
```
            if (etag != null && etag.length() > 0) {
                md.update(BinaryUtils.fromHex(etag.toLowerCase()));
            }
```

**Comment by kananindzya** [comment]
Now, I am catching new exception:
in this part:
```
final StreamTransferManager uploadManager = StreamTransferManagerFactory.create(bucket, fullObjectKey, s3Client)
        .setPartSize(partSize)
        .setUserMetadata(metadata)
        .get()
        .checkIntegrity(true)
        .numUploadThreads(1)
        .queueCapacity(DEFAULT_QUEUE_CAPACITY);
    boolean succeeded = false;

    // Wrap output stream in decorators
    OutputStream rawOutputStream = uploadManager.getMultiPartOutputStreams().get(0);
    for (final BlobDecorator blobDecorator : blobDecorators) {
      rawOutputStream = blobDecorator.wrap(rawOutputStream);
    }

    try (final OutputStream outputStream = rawOutputStream;
        final InputStream dataStream = recordsData.getInputStream()) {
      dataStream.transferTo(outputStream);
      succeeded = true;
    } catch (final Exception e) {
      LOGGER.error("Failed to load data into storage {}", objectPath, e);
      throw new RuntimeException(e);
    } finally {
      if (!succeeded) {
        uploadManager.abort();
      } else {
        uploadManager.complete();
      }
    }
```
```
2022-08-09 05:36:23 destination > 2022-08-09 05:36:23 ERROR i.a.i.d.s.S3StorageOperations(uploadRecordsToBucket):129 - Failed to upload records into storage csv_test_T26yL/boolean_test_1/2022_08_09_1660023378371_
2022-08-09 05:36:23 destination > java.lang.RuntimeException: java.io.IOException: Stream Closed
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3StorageOperations.loadDataIntoBucket(S3StorageOperations.java:186) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3StorageOperations.uploadRecordsToBucket(S3StorageOperations.java:127) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3ConsumerFactory.lambda$flushBufferFunction$2(S3ConsumerFactory.java:133) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.flushAll(SerializedBufferingStrategy.java:103) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:172) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:147) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.r2.R2Destination.main(R2Destination.java:51) [io.airbyte.airbyte-integrations.connectors-destination-r2-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > Caused by: java.io.IOException: Stream Closed
2022-08-09 05:36:23 destination > 	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
2022-08-09 05:36:23 destination > 	at java.io.FileInputStream.read(FileInputStream.java:276) ~[?:?]
2022-08-09 05:36:23 destination > 	at java.io.InputStream.transferTo(InputStream.java:782) ~[?:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3StorageOperations.loadDataIntoBucket(S3StorageOperations.java:182) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	... 8 more
2022-08-09 05:36:23 destination > 2022-08-09 05:36:23 INFO i.a.i.d.r.FileBuffer(deleteFile):81 - Deleting tempFile data bf988420-c2e9-470b-a9f6-2b1c975ec7af15665291246012729536.csv
2022-08-09 05:36:23 destination > 2022-08-09 05:36:23 ERROR i.a.i.d.s.S3ConsumerFactory(lambda$flushBufferFunction$2):140 - Failed to flush and upload buffer to storage:
2022-08-09 05:36:23 destination > java.lang.RuntimeException: Exceptions thrown while uploading records into storage: java.lang.ArrayIndexOutOfBoundsException: Index 106 out of bounds for length 103
2022-08-09 05:36:23 destination > java.lang.RuntimeException: java.io.IOException: Stream Closed
2022-08-09 05:36:23 destination > java.lang.RuntimeException: java.io.IOException: Stream Closed
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3StorageOperations.uploadRecordsToBucket(S3StorageOperations.java:133) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.s3.S3ConsumerFactory.lambda$flushBufferFunction$2(S3ConsumerFactory.java:133) ~[io.airbyte.airbyte-integrations.bases-base-java-s3-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.flushAll(SerializedBufferingStrategy.java:103) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:172) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
2022-08-09 05:36:23 destination > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:64) [io.airbyte.airbyte-integrations.bases-base-java-0.39.41-alpha.jar:?]
```

**Comment by kananindzya** [comment]
@alexmojaki I found different:

cloudflare r2 returns very long etag value, like below:

```
AMClbuttcYqB7BF87QMg3AoksQpTl1irPgMPSw1tRzTVHdOG0Lg5IsXKRfsyI5XIf7BpGvF7qu5JcpeytpWjNsOLT8l8LNhf2r86HO06zTouao5TXV0NqZ2EBsCP13WiC+g1B2xIJy4I3NhcPEw5COEreGlzt9pHTg7NK1+H4rpzcS54uyZ3CmRZI5V3ksG6t+6maCEbVAROkPIn6/61xOqQvYPWy9pF9jOwREBsvsEtwzqKKEaGIz9n8V2ckJTX2w==
```

aws s3 returns - 7e1699ce7c4480424036fefdfa9dd378

**Comment by kananindzya** [comment]
as a workaround, I disabled the check Integrity.

**Comment by alexmojaki** [comment]
See https://github.com/alexmojaki/s3-stream-upload/pull/26#discussion_r400436141 and the note in http://alexmojaki.github.io/s3-stream-upload/javadoc/apidocs/alex/mojaki/s3upload/StreamTransferManager.html#checkIntegrity-boolean- :

> Note that AWS doesn't document this, so their hashing algorithm might change without notice which would lead to false alarm exceptions.

Basically, the hashing algorithm is 'unofficial', and it sounds like cloudflare is doing something different from AWS. That's why `checkIntegrity` is disabled by default.

**Comment by kananindzya** [comment]
NOTE: `AmazonS3Client` does same check, this can be disabled with setting system properties:
```
    System.setProperty( "com.amazonaws.services.s3.disableGetObjectMD5Validation", "true");
    System.setProperty( "com.amazonaws.services.s3.disablePutObjectMD5Validation", "true");
```
