### ISSUE TITLE
AmazonS3Exception: One or more of the specified parts could not be found

### ISSUE THREAD

**Issue by vickichowder** [alexmojaki/s3-stream-upload#6]
I am getting this error when I upload using a single stream (because I need to preserve order), and I am using WebFlux to subscribe to the response and trigger the upload as the`.subscribe()` gets called.
Is there anything that I am doing wrong that causes the parts to be not uploaded (even though the logs say that it has been uploaded)?

I've traced the request down to the AmazonS3Client `invoke()` method to ensure that the upload id is still the same, and that the part id for the single part is also the same. 

**Code**
```java
    private void uploadToS3(String reportName, Map<String, String> urlParameters,
        StreamTransferManager transferManager,
        MultiPartOutputStream outputStream) {

        Flux<String> response = reportService.streamReport(reportName, urlParameters);

        ExecutorService pool = Executors.newFixedThreadPool(singleThread);

        pool.submit(() -> {
            response
                .doOnComplete(() -> {
                    log.info("Completing upload response");
                    outputStream.close();
                    pool.shutdown();
                    try {
                        pool.awaitTermination(5, TimeUnit.SECONDS);
                    } catch (InterruptedException e) {
                        log.error("Could not await pool termination");
                    }
                    transferManager.complete();
                    log.info("Uploaded file to s3");
                })
                .doOnError(error -> {
                    outputStream.close();
                    transferManager.abort(error);
                })
                .subscribe(csvLine -> {
                    try {
                        outputStream.write(String.format("%s\n", csvLine).getBytes("UTF-8"));
                    } catch (UnsupportedEncodingException e) {
                        log.error("Can't read/get bytes: %s", e);
                    }
                    try {
                        outputStream.checkSize();
                    } catch (InterruptedException e) {
                        log.error("Wut happened: %s", e);
                    }
                });
        });
    }
```

**Error message**
```
2018-07-27 11:18:15.238  INFO 94733 --- [enerContainer-2] a.mojaki.s3upload.StreamTransferManager  : Initiated multipart upload to filepath/**reportName**.csv with full ID OpSTbPRdvIyZvhtnTMWplZzghIaRrm7lh3VzSUI00bkdNZUUL/hwjVJdWQ
2018-07-27 11:18:34.089  INFO 94733 --- [ctor-http-nio-4] c.s.p.rqindigestor.sqs.SQSSubscriber     : Completing upload response
2018-07-27 11:18:34.089  INFO 94733 --- [ctor-http-nio-4] a.mojaki.s3upload.MultiPartOutputStream  : Called close() on [MultipartOutputStream for parts 1 - 10000]
2018-07-27 11:18:34.091  INFO 94733 --- [ctor-http-nio-4] a.mojaki.s3upload.StreamTransferManager  : [Part number 1 containing 1.16 MB]: Uploading leftover stream {}
2018-07-27 11:18:34.322  INFO 94733 --- [ctor-http-nio-4] a.mojaki.s3upload.StreamTransferManager  : [Manager uploading to filepath/*****.csv with id OpSTbPRdv.../hwjVJdWQ]: Finished uploading [Part number 1 containing 1.16 MB]
2018-07-27 11:18:34.415 ERROR 94733 --- [ctor-http-nio-4] a.mojaki.s3upload.StreamTransferManager  : [Manager uploading to filepath/**reportname**.csv with id OpSTbPRdv.../hwjVJdWQ]: Abort called due to error:

com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: null; S3 Extended Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1640) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.372.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4368) ~[aws-java-sdk-s3-1.11.372.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4315) ~[aws-java-sdk-s3-1.11.372.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3100) ~[aws-java-sdk-s3-1.11.372.jar:na]
	at alex.mojaki.s3upload.StreamTransferManager.complete(StreamTransferManager.java:217) ~[s3-stream-upload-1.0.1.jar:na]
	at com.processing.sqs.SQSSubscriber.lambda$null$1(SQSSubscriber.java:140) [classes/:na]
```

**Comment by vickichowder** [comment]
[UPDATE]
I noticed that `transferManager.complete()` was being called before all parts had finished uploading (after `close()` is called, there are more logs of parts being uploaded). However, `transferManager.close()` should wait for the MultiPartOutputStreams to finish first still - and this shouldn't be the cause of the problem?

**Comment by alexmojaki** [comment]
The logs look fine. As you say, it's normal for uploading to happen after calling `complete()`.

See if you can enable debug level logging. This library will spit out some extra logs and the AWS SDK probably will too, and maybe that'll have some clues.

Ideally, if you can provide code that reproduces this problem that I can actually run myself, I can try to debug this for you.

You shouldn't need an `ExecutorService` for this. I don't think it's causing the problem, but maybe remove it?

**Comment by vickichowder** [comment]
Thanks, I'll try removing the ExecutorService and see how that goes ✌️

**Comment by vickichowder** [comment]
Removing `ExecutorService` does not change the output 
Here is the code that captures data from an endpoint and attempts to stream it to s3: (the method `streamFromEndpointToS3() is the starting point`)
```
import alex.mojaki.s3upload.MultiPartOutputStream;
import alex.mojaki.s3upload.StreamTransferManager;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.UploadPartRequest;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.util.Date;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.util.UriComponentsBuilder;
import reactor.core.publisher.Flux;

public class Sample {
    private static final Logger log = LoggerFactory.getLogger(Sample.class);

    AmazonS3 amazonS3 = AmazonS3ClientBuilder.standard()
        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:4572", "us-east-1"))
        .build();

    public Flux<String> streamFromEndpoint() {
        // returns a csv response
        String endpoint = "http://www.mocky.io/v2/5b5f1ff32e00007d0069484f";
        UriComponentsBuilder builder = UriComponentsBuilder.fromUriString(endpoint);
        URI uri = builder.build().toUri();

        WebClient webClient = WebClient.builder().build();

        return webClient.get()
            .uri(uri)
            .retrieve()
            .bodyToFlux(String.class);
    }

    private void uploadToS3(StreamTransferManager transferManager,
        MultiPartOutputStream outputStream
    ) {
        Flux<String> response = streamFromEndpoint();

        response
            .doOnComplete(() -> {
                outputStream.close();
                transferManager.complete();
                log.info("Uploaded file to s3");
            })
            .doOnError(error -> {
                transferManager.abort(error);
                try {
                    outputStream.close();
                } catch (Exception e) {
                    log.warn(String.format("Output stream could not be closed: %s", e));
                }
            })
            .subscribe(csvLine -> {
                try {
                    outputStream.write(String.format("%s\n", csvLine).getBytes("UTF-8"));
                } catch (UnsupportedEncodingException e) {
                    log.error("Can't read/get bytes: %s", e);
                }
                try {
                    outputStream.checkSize();
                } catch (InterruptedException e) {
                    log.error("Wut happened: %s", e);
                }
            });
    }

    private void streamFromEndpointToS3() {
        String bucketName = "dummyBucket";
        String filepath = "dummy/file.csv";

        // CustomStreamTransferManager extends StreamTransferManager
        final CustomStreamTransferManager transferManager = new CustomStreamTransferManager(
            bucketName,
            filepath,
            amazonS3,
            1,
            1,
            1,
            5);
        final List<MultiPartOutputStream> outputStreams = transferManager
            .getMultiPartOutputStreams();

        uploadToS3(transferManager, outputStreams.get(0));
    }

    public class CustomStreamTransferManager extends StreamTransferManager {

        public CustomStreamTransferManager(String bucketName, String putKey,
            AmazonS3 s3Client, int numStreams, int numUploadThreads,
            int queueCapacity, int partSize) {
            super(bucketName, putKey, s3Client, numStreams, numUploadThreads, queueCapacity,
                partSize);
        }

        @Override
        public void customiseUploadPartRequest(UploadPartRequest request) {
            ObjectMetadata objectMetadata = new ObjectMetadata();
            objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
            request.setObjectMetadata(objectMetadata);
        }
    }
}
```

**Comment by alexmojaki** [comment]
Please tell me exactly what dependencies I need, preferably in the form of something like a maven `pom.xml` file.

I see `http://localhost:4572` - what is that and how do I set it up? Does the problem still appear if you use the real AWS S3? I would prefer to use the real S3 for this test.

**Comment by vickichowder** [comment]
[pom.txt](https://github.com/alexmojaki/s3-stream-upload/files/2242402/pom.txt)
Github won't let me upload an xml file, so I've put it in txt

As for the localhost:4572, that's the s3 endpoint from using aws localstack (https://github.com/localstack/localstack), a localized AWS. I haven't tried this with real s3 yet, so this may be a good time for me to do so 👍

**Comment by vickichowder** [comment]
Thank you for your help!
This works perfectly fine the moment I switch from using localstack s3 to use real AWS s3!
🙌
